### ISSUE TITLE
Issue with bleed-none

### ISSUE THREAD

**Issue by sayjeyhi** [dgknca/tailwindcss-full-bleed#3] opened 2024-01-04 16:24 UTC
if we have an element with a border(like a box) and we want to bleed the border on mobile, having `bleed-none` on `md:` will change the border color on the desktop to black. the reason is that we are just changing the width of the border on bleed none.

the solution for me was changing the `bleed-border` family to include `var(--tw-full-bleed-color)`, so this way we will have:
```js
'border-bottom',
 'var(--tw-full-bleed-border-bottom-width) solid var(--tw-full-bleed-color)',
```

and it will prevent the issue from happening

**Comment by sayjeyhi** [comment] 2024-01-04 16:26
I provided the fix for this issue @dgknca

**Comment by dgknca** [comment] 2024-01-05 06:48
Hi @sayjeyhi . Thanks for the issue. But i can't reproduce what you said. Can you create a minimal repo that reproduces the issue you're experiencing? Or you can just give me the css you wrote. I checked this and didn't see any problem:

```
size-40 bleed-border-t-2 bleed-red-500 md:bleed-none
```

**Comment by sayjeyhi** [comment] 2024-01-05 18:34
@dgknca you need to have a border on the desktop:
`size-40 bleed-border-t-2 bleed-red-500 md:bleed-none md:border-gray-200`

then in desktop the border top and bottom will be effected

**Comment by dgknca** [comment] 2024-01-06 19:03
I tried your code and still can't see any border on desktop. Can you create a project from scratch (with [create-next-app](https://nextjs.org/docs/pages/api-reference/create-next-app) etc.) and try again to see if your issue related to the plugin?

**Comment by sayjeyhi** [comment] 2024-01-07 00:10
Create an app in next.js 14 and replace page.js/ts with this:

```

export default function Home() {
  return (
    <div className="max-w-[400px] mx-auto p-9 my-24 border border-amber-700">
      <div className="size-64 flex flex-col items-center border-2 border-amber-700 rounded-2xl bleed-border bleed-red-500 md:bleed-none">
        TEST
      </div>
    </div>
  )
}
```

Sample app:

[reproduce.zip](https://github.com/dgknca/tailwindcss-full-bleed/files/13851753/reproduce.zip)

In desktop the top and bottom borders are dark but I applied `amber-700`
<img width="548" alt="Screenshot 2024-01-07 at 01 10 50" src="https://github.com/dgknca/tailwindcss-full-bleed/assets/6254009/a21a4252-7387-4763-857b-f68677e9ea39">

In Mobile bleed is fine:

<img width="705" alt="Screenshot 2024-01-07 at 01 11 34" src="https://github.com/dgknca/tailwindcss-full-bleed/assets/6254009/ff84f0c9-2c6d-498f-95cd-3c44777f4cd2">

**Comment by dgknca** [comment] 2024-01-07 11:27
I just reviewed it and see the issue. So you want to have bleeding borders at the top and bottom on mobile only and regular borders on desktop, right? if you do this `md:border-2 md:border-amber-700` it will work fine. (it's not dark, there is no top-bottom border on desktop)

In the PR, you added `var(--tw-full-bleed-color)` to the border colors but here it doesn't matter what the border color is. Bleed color is specified in `border-image`. If you will have `bleed-none` on `md` breakpoint, you shouldn't care about anything from bleed classes from lower breakpoints. We should say "I reset the bleeding on md, so I no longer have to consider anything from it". But if you add `var(--tw-full-bleed-color)` in bleed borders, you say you want to use this fallback color even if you reset the bleeding. It's not a best-practice. (In your situation this won't work too, because border-top and bottom widths are 0. You will need to make `md:border-2` anyway) You should specify border-width and color after resetting the bleed.

**Comment by sayjeyhi** [comment] 2024-01-10 16:11
Well, actually in my case it was happening and I couldn't find any other solution and cloned the repo and using the cloned one, anyways thanks for the great work

**Comment by dgknca** [comment] 2024-01-10 19:19
ok. I'm always here for help. Closing this now.

**Closed as completed by dgknca** 2024-01-10 19:19 UTC
